language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - rbx-19mode

before_install:
  - sudo apt-get -qq -y --force-yes update

notifications:
  irc: "irc.freenode.net#jovelabs"

matrix:
  include:
    - rvm: jruby-18mode
      env: JRUBY_OPTS="--1.8 -Xcext.enabled=true"
    - rvm: jruby-19mode
      env: JRUBY_OPTS="--1.9 -Xcext.enabled=true"
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ree
