language: ruby

rvm:
  - 1.9.2
  - 1.9.3

before_install:
  - sudo apt-get -qq --force-yes update

bundler_args: --binstubs

script: "bin/rake test"

notifications:
  irc: "irc.freenode.net#jovelabs"
